//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace zÉbET.ZEBET_verFinal.Main.DESPORTOS {
    
    
    public partial class tennis {
    }
}
